name: flutter_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.13.0
  cached_network_image: ^2.3.3
  qr_code_scanner: ^0.0.13
  awesome_dialog: ^1.2.1
  intl:
  calendar_flutter: ^1.1.5















  table_calendar: ^2.3.0
  marquee: ^1.6.1
  connectivity: ^2.0.1

  #Firebase
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/signUpMethods/
